//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Teams Graph Connect Sample for ASP.NET 4.6.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Teams Graph Connect C# Sample.
        /// </summary>
        internal static string App_Name_Short {
            get {
                return ResourceManager.GetString("App_Name_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller needs to authenticate..
        /// </summary>
        internal static string Error_AuthChallengeNeeded {
            get {
                return ResourceManager.GetString("Error_AuthChallengeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string Error_Introduction {
            get {
                return ResourceManager.GetString("Error_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in.
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed, but no results were returned..
        /// </summary>
        internal static string No_Results {
            get {
                return ResourceManager.GetString("No_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID  :.
        /// </summary>
        internal static string Prop_ID {
            get {
                return ResourceManager.GetString("Prop_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Microsoft.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Channel Id.
        /// </summary>
        internal static string TeamsGraph_Channel_Id_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_Channel_Id_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string TeamsGraph_CreateChannel_Button {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateChannel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Channel Description:.
        /// </summary>
        internal static string TeamsGraph_CreateChannel_Description_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateChannel_Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Channel.
        /// </summary>
        internal static string TeamsGraph_CreateChannel_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateChannel_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Channel Name:.
        /// </summary>
        internal static string TeamsGraph_CreateChannel_Name_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateChannel_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! New channel is created..
        /// </summary>
        internal static string TeamsGraph_CreateChannel_Success_Result {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateChannel_Success_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        internal static string TeamsGraph_CreateGroup_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateGroup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! New group is created..
        /// </summary>
        internal static string TeamsGraph_CreateGroup_Success_Result {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateGroup_Success_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string TeamsGraph_CreateMember_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateMember_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team to Group.
        /// </summary>
        internal static string TeamsGraph_CreateTeam_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_CreateTeam_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string TeamsGraph_GetChannels_Button {
            get {
                return ResourceManager.GetString("TeamsGraph_GetChannels_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Channels.
        /// </summary>
        internal static string TeamsGraph_GetChannels_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_GetChannels_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels Information.
        /// </summary>
        internal static string TeamsGraph_GetChannels_Results_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_GetChannels_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string TeamsGraph_GetMyTeams_Button {
            get {
                return ResourceManager.GetString("TeamsGraph_GetMyTeams_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get My Teams.
        /// </summary>
        internal static string TeamsGraph_GetMyTeams_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_GetMyTeams_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Information.
        /// </summary>
        internal static string TeamsGraph_GetMyTeams_Results_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_GetMyTeams_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string TeamsGraph_PostMessage_Button {
            get {
                return ResourceManager.GetString("TeamsGraph_PostMessage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Message.
        /// </summary>
        internal static string TeamsGraph_PostMessage_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_PostMessage_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Message.
        /// </summary>
        internal static string TeamsGraph_PostMessage_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_PostMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your message is posted..
        /// </summary>
        internal static string TeamsGraph_PostMessage_Success_Result {
            get {
                return ResourceManager.GetString("TeamsGraph_PostMessage_Success_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is posted using Teams Graph API..
        /// </summary>
        internal static string TeamsGraph_PostMessage_Text {
            get {
                return ResourceManager.GetString("TeamsGraph_PostMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Team Id.
        /// </summary>
        internal static string TeamsGraph_Team_Id_Label {
            get {
                return ResourceManager.GetString("TeamsGraph_Team_Id_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Team.
        /// </summary>
        internal static string TeamsGraph_UpdateTeam_Heading {
            get {
                return ResourceManager.GetString("TeamsGraph_UpdateTeam_Heading", resourceCulture);
            }
        }
    }
}
